exp_name   : Test
device     : cuda
debug      : False
analysis   : True

defaults:
  - _self_
  - model: Conv_Pool
  - dataset : EEG

dir:
  input        : /work/abelab4/k_hiro/study/HMS/data

train:
  batch_size  : 32
  epochs      : 500
  test_size   : 0.2

optim:
  learning_rate: 0.001
  weight_decay : 0.0001

lr_scheduler:
  step   : 40
  gamma  : 0.8

step:
  log   : 50
  save  : 10000
  valid : 250
