exp_name   : Test
device     : cuda
debug      : False

defaults:
  - _self_
  - model: LSTM_Pool

dataset : EEGDataset

dir:
  input        : ./data

train:
  batch_size  : 16
  epochs      : 500
  test_size   : 0.1

optim:
  learning_rate: 0.001
  weight_decay : 0.0001

lr_scheduler:
  step   : 40
  gamma  : 0.8

step:
  log   : 50
  save  : 5000
  valid : 250