name       : Conv-LSTM
debug      : False

defaults:
  - _self_
  - model: Conv_LSTM

dir:
  input        : ./data

train:
  batch_size  : 32
  epochs      : 200
  test_size   : 0.1

optim:
  learning_rate: 0.001
  weight_decay : 0.0001

lr_scheduler:
  step   : 40
  gamma  : 0.1

step:
  log   : 50
  save  : 5000
  valid : 500